# Generated by Django 5.2.2 on 2025-06-10 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('idDepartamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDepa', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.AutoField(primary_key=True, serialize=False)),
                ('primerNombre', models.CharField(max_length=30)),
                ('segundoNombre', models.CharField(max_length=30)),
                ('tercerNombre', models.CharField(max_length=30)),
                ('primerApellido', models.CharField(max_length=30)),
                ('segundoApellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('CUI', models.CharField(max_length=13)),
                ('fechaNac', models.DateField()),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('puesto', models.CharField(max_length=100)),
                ('fechaContratacion', models.DateField()),
                ('salarioBase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido'), ('Vacaciones', 'Vacaciones')], default='Activo', max_length=15)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.departamento')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empleado.persona')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='jefeDepartamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_dirigidos', to='empleado.empleado'),
        ),
    ]
